#!/bin/bash

wal --theme base16-gruvbox-soft -l -o ~/.config/dunst/launchdunst.sh
gsettings set org.gnome.desktop.interface gtk-theme "Arc"
killall DiscordCanary
i3-msg "Workspace 3; exec discord-canary"
sed -i 's/light/dark/g' ~/.config/rofi/config.rasi
sed -i 's/Dark/Light/g' ~/.config/Code/User/settings.json
sed -i 's/set background=dark/set background=light/g' ~/.vimrc
