#!/bin/bash

# TODO USB-C external monitors (where main bar should be on external)

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# ThinkPad X1 Carbon Gen 9; 14 inch 1920x1200
export INTERNAL_MONITOR="eDP-1"

if [ `xrandr | grep "HDMI-1" | grep -c ' connected '` -eq 1 ]; then
	# LG 27GL83A-B 27-inch 2560x1440 monitor
	export EXTERNAL_MONITOR="HDMI-1"
	exec polybar -c ~/.config/polybar/config main-on-ext-monitor &
	exec polybar -c ~/.config/polybar/config secondary-on-laptop &
elif [ `xrandr | grep "DP-2" | grep -c ' connected '` -eq 1 ]; then
	# ASUS MB16ACE 16-inch 1920x1080 portable monitor
	export EXTERNAL_MONITOR="DP-2"
	exec polybar -c ~/.config/polybar/config main-on-laptop &
	exec polybar -c ~/.config/polybar/config secondary-on-portable-monitor &
elif [ `xrandr | grep "DP-3" | grep -c ' connected '` -eq 1 ]; then
	# ASUS MB16ACE 16-inch 1920x1080 portable monitor
	export EXTERNAL_MONITOR="DP-3"
	exec polybar -c ~/.config/polybar/config main-on-laptop &
	exec polybar -c ~/.config/polybar/config secondary-on-portable-monitor &
else
	exec polybar -c ~/.config/polybar/config main-on-laptop &
fi
