#!/usr/bin/env python
import sys, requests, json, re, time
import pywal

colors = pywal.colors.file("/home/asaligrama/.cache/wal/colors.json")["colors"]

f = open("/home/asaligrama/.openweather", "r")
api_key = f.readline().strip()
latlon = f.readline().strip().split(",")

url = f"https://api.openweathermap.org/data/2.5/onecall?lat={latlon[0]}&lon={latlon[1]}&appid={api_key}&units=imperial"

try:
    weather_json = requests.get(url)
    weather_json.raise_for_status()
    data = json.loads(weather_json.content.decode())
except:
    exit()

icon = ""
descr = data["current"]["weather"][0]["id"]
if descr == 800 or descr == 801 or descr == 802:  # clear or partly cloudy
    if (
        int(time.time()) > data["current"]["sunrise"]
        and int(time.time()) < data["current"]["sunset"]
    ):
        icon = ""
    else:
        icon = ""
elif descr >= 600 and descr < 700:  # snow
    icon = ""
elif descr >= 200 and descr < 600:  # rain (various intensity)
    icon = ""
elif (
    (descr >= 601 and descr < 800) or descr == 803 or descr == 804
):  # clouds/atmospheric
    icon = ""

temp = data["current"]["temp"]
color = ""

if temp <= 45.0:
    color = colors["color13"]
elif temp > 45.0 and temp <= 60.0:
    color = colors["color6"]
elif temp > 60.0 and temp <= 80.0:
    color = colors["color2"]
else:
    color = colors["color1"]

print(f"%{{B{color}}}  {icon} {str(int(round(temp, 0)))} °F  ")
